#!/usr/bin/env node
// Copies the published theme-sdk bridge into a TS constant so `arinova theme dev`
// serves the EXACT production bridge (dev === prod) with no runtime file lookup
// and no extra dependency. Runs as arinova-cli's `prebuild`. Tolerant: if the
// theme-sdk source is not present (e.g. a standalone checkout), it keeps the
// already-generated file instead of failing the build.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "..", "theme-sdk", "src", "bridge.js");
const outDir = join(here, "..", "src", "generated");
const out = join(outDir, "theme-bridge.ts");

if (!existsSync(src)) {
  console.warn(`[inline-bridge] source not found at ${src}; keeping existing ${out}`);
  process.exit(0);
}

const bridge = readFileSync(src, "utf-8");
const body = `// AUTO-GENERATED by scripts/inline-bridge.mjs from @arinova-ai/theme-sdk (src/bridge.js).
// Do not edit by hand — run \`pnpm --filter @arinova-ai/cli build\` (or \`node scripts/inline-bridge.mjs\`).
export const THEME_BRIDGE = ${JSON.stringify(bridge)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(out, body);
console.log(`[inline-bridge] wrote ${out} (${bridge.length} bytes)`);
